server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbite_resource_db
    username: postgres
    password: database.postgreSQL00?
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

keySetUri: http://10.66.66.9:8080/oauth2/jwks
