spring:
  application:
    name=resource-server
  datasource:
    url: jdbc:postgresql://localhost:5432/springbite_resource_db
    username: postgres
    password: database.postgreSQL00?
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
