server:
  address: 10.66.66.9

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbite_authorization_db
    username: postgres
    password: database.postgreSQL00?
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

trusted:
  issuers:
    - https://accounts.google.com
  clients:
    - 622455662282-vfr0an7e1hdunsifk1vke9duun486pfi.apps.googleusercontent.com

csrf:
  whiteSetUris:
    - /login
    - /signup/**
    - /auth/**
    - /accounts/**